chore: setup CI for terraform (#6)

diff --git a/terraform/justfile b/terraform/justfile
--- a/terraform/justfile
+++ b/terraform/justfile
@@ -4,7 +4,7 @@ default:
     @just --list
 
 release: test it
-    @just jsonnet-release terraform
+    @jsonnet-kit release -r https://github.com/marcbran/jsonnet.git
 
 test:
     @jsonnet-kit test
@@ -12,28 +12,41 @@ test:
 it:
     #!/usr/bin/env bash
     echo "Running integration tests..."
-    pushd it
 
-    echo "Starting Docker Compose..."
     exit_code=0
+    passed=0
+    total=0
     while read -r tst; do
-      it="$(echo "${tst}" | jq -r '.[0]')"
-      if [ "${it}" != "true" ]; then
+
+      name="$(echo "${tst}" | jq -r '.name')"
+      echo "${name}"
+
+      total=$((total + 1))
+
+      mkdir -p tf
+      echo "${tst}" | jq -r '.actual' > tf/main.tf.json
+
+      if ! output=$(terraform -chdir=tf init 2>&1); then
+        echo "terraform init failed for content: ${content}"
+        echo "$output"
+        exit_code=1
+        rm -rf tf
         continue
       fi
 
-      actual="$(echo "${tst}" | jq -r '.[1]')"
-      mkdir -p tf
-      touch tf/example.txt
-      echo "${actual}" > tf/main.tf.json
-      terraform -chdir=tf init
-      terraform -chdir=tf plan
-      rm -rf tf
-    done < <(jsonnet '../main_tests.libsonnet' | jq -rc 'map([.it, .actual]) | .[]')
+      if ! output=$(terraform -chdir=tf plan 2>&1); then
+        echo "terraform plan failed for content: ${content}"
+        echo "$output"
+        exit_code=1
+        rm -rf tf
+        continue
+      fi
 
-    if [ "${exit_code}" -eq 0 ]; then
-      echo "All tests passed!"
-    else
-      echo "Some tests failed!"
-    fi
+      passed=$((passed + 1))
+
+      rm -rf tf
+
+    done < <(jsonnet-kit test --json | jq -rc '.results | .[]')
+
+    echo "Passed: ${passed}/${total}"
     exit "${exit_code}"
